// Country list for the demo form. The three most common institutional
// markets are pinned to the top; the rest follow alphabetically.
export const COUNTRIES: string[] = [
  "United States",
  "United Kingdom",
  "Singapore",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Belgium",
  "Bermuda",
  "Brazil",
  "British Virgin Islands",
  "Canada",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Gibraltar",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jersey",
  "Jordan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Monaco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saudi Arabia",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "Vietnam",
  "Other",
];
